name: Latest blog post workflow
on: 
  schedule:
    - cron: '30 18 * * SUN'
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blogs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@smc181002,https://smc181002.hashnode.dev/rss.xml,https://smc181002.github.io/rss.xml"
